# Generated by Django 4.0.2 on 2022-02-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=200)),
                ('line_two', models.CharField(max_length=200)),
                ('line_three', models.CharField(max_length=200)),
                ('line_four', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
            ],
        ),
    ]
